# This secret is used to store cloud services credentials
{{- if and .Values.global.postgres.usePercona (not .Values.common.postgres.postgresPassword) (not .Values.common.postgres.postgresPasswordSecretName) (not .Values.common.postgres.postgresPasswordSecretKey) }}

{{- $fullname := include "agenticbuilder.fullname" . }}
{{- $secretname := printf "%s-postgres-password" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace $secretname }}
apiVersion: v1
kind: Secret
metadata: 
  name: "{{ $secretname }}"
  annotations:
    helm.sh/resource-policy: keep
data:
  {{- if $previous.data }}
  postgres-password: {{ index $previous.data "postgres-password" }}
  {{ else }}
  postgres-password: {{ randAlphaNum 32 | b64enc | b64enc | quote }}
  {{ end }}
{{- end }}