######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021, 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "fullname" . }}
{{ $saName := include "uno.serviceAccount" . }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ $saName }}
  labels:
{{ include "uno.common.label" . | indent 4 }}
imagePullSecrets:
{{- $secret1 := lookup "v1" "Secret" .Release.Namespace "sa-uno" }}
{{- if $secret1 }}
  - name: sa-uno
{{- else }}
  # Secret 'sa-uno' not found in namespace {{ .Release.Namespace }}
{{- end }}
{{- $secret2 := lookup "v1" "Secret" .Release.Namespace (printf "sa-%s" .Release.Namespace) }}
{{- if $secret2 }}
  - name: sa-{{ .Release.Namespace }}
{{- else }}
  # Secret 'sa-{{ .Release.Namespace }}' not found in namespace {{ .Release.Namespace }}
{{- end }}
{{- if .Values.global.hclImagePullSecret }}
  - name: {{ .Values.global.hclImagePullSecret }}
{{- end }}



