# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
{{ $secretname := printf "%s-%s" .Release.Name  "uno-secret" }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace  $secretname }}
metadata:
  name: {{ $secretname }}
  labels:
{{- if $previous }}
    update-secret: "true"
{{ end }}
{{ include "uno.common.label" . | indent 4 }}
type: "Opaque"
data:
  AGENT_API_KEY: {{ .Values.agent.configuration.apiKeySecret | default "" | b64enc | quote }}