####################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
####################################################################
# WARNING: This file contain secret object to use in AWS Marketplace deployment 
apiVersion: v1
kind: Secret
metadata:
  name: wa-pwd-secret
  labels:
{{ include "uno.chart.common.label" . | indent 4 }}
type: "Opaque"
{{- $previous := lookup "v1" "Secret" .Release.Namespace  "wa-pwd-secret" }}
data:
  {{- if (($previous).data).WA_PASSWORD }}
  WA_PASSWORD: {{ $previous.data.WA_PASSWORD }}
  {{- else if .Values.global.wapassword }}
  WA_PASSWORD: {{ .Values.global.wapassword | b64enc | quote }}
  {{- else }}
  WA_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
  {{- end }}
  {{- if (($previous).data).DB_ADMIN_PASSWORD }}
  DB_ADMIN_PASSWORD: {{ $previous.data.DB_ADMIN_PASSWORD }}
  {{- else if .Values.global.dbadminpassword }}
  DB_ADMIN_PASSWORD: {{ .Values.global.dbadminpassword | b64enc | quote }}
  {{- end }}
  {{- if (($previous).data).DB_PASSWORD }}
  DB_PASSWORD: {{ $previous.data.DB_PASSWORD }}
  {{- else if .Values.global.dbpassword  }}
  DB_PASSWORD: {{ .Values.global.dbpassword  | b64enc | quote }}
  {{- end }}
