######################################################################
# Licensed Materials Property of HCL*
# (c) Copyright HCL Technologies Ltd. 2021, 2023. All rights reserved.
#
# * Trademark of HCL Technologies Limited
######################################################################
{{ $fullName := include "fullname" . }}

{{- if gt .Values.deployment.global.maxTargetReplicas .Values.deployment.global.minTargetReplicas }}
{{- $root := . -}}

{{- $myList := include "uno.microservices.list" . | fromJsonArray -}}
{{- range $myList}}

{{- if $root.Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else if $root.Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
apiVersion: autoscaling/v2beta2
{{- else }}
apiVersion: autoscaling/v1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ $fullName }}-{{ . }}
  labels:
{{ include "uno.common.label" $root | indent 4 }}

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}-{{ . }}
  minReplicas: {{ coalesce (index $root.Values.deployment . ).minTargetReplicas $root.Values.deployment.global.minTargetReplicas }}
  maxReplicas: {{ coalesce (index $root.Values.deployment . ).maxTargetReplicas $root.Values.deployment.global.maxTargetReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ coalesce ((index $root.Values.deployment . ).autoscaler).cpuAverageUtilization $root.Values.deployment.global.autoscaler.cpuAverageUtilization }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Max
#- type: Resource
#  resource:
#    name: memory
#    target:
#      type: AverageValue
#      averageValue: 500Mi
#- type: Object
#  object:
#      metric:
#        name: requests-per-second
#      describedObject:
#        apiVersion: networking.k8s.io/v1beta1
#        kind: Ingress
#        name: main-route
#      target:
#        type: Value
#        value: 10k

---
{{- end}}
{{- end}}
