# *******************************************************************************
# Licensed Materials - Property of HCL
# (c) Copyright HCL Technologies Ltd. 2024. All Rights Reserved.
# 
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# *******************************************************************************
{{ $fullName := include "fullname" . }}
{{ $root := . -}}
{{- $agenticImageRepo := .Values.agenticAIBuilder.image.repository -}}
{{- $agenticImageTag := .Values.agenticAIBuilder.image.tag -}}
{{- $deploymentIdSource := printf "%s:%s" $agenticImageRepo $agenticImageTag -}}
{{- $productDeploymentId := $deploymentIdSource | sha256sum | trunc 32 -}}

apiVersion:  v1
kind:  ConfigMap
metadata: 
  name: "{{ $fullName }}-uno-deployment-config"
  labels:
{{ include "uno.common.label" . | indent 4 }}
data:
  PRODUCT_DEPLOYMENT_ID: "{{ $productDeploymentId }}"
  AGENTICAI_IMAGE_REPOSITORY: "{{ $agenticImageRepo }}"
  AGENTICAI_IMAGE_TAG: "{{ $agenticImageTag }}" 

