# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
{{ $secretname := printf "%s-%s" .Release.Name  "uno-secret" }}
{{- $previous := lookup "v1" "Secret" .Release.Namespace  $secretname }}
metadata:
  name: {{ $secretname }}
  labels:
{{- if $previous }}
    update-secret: "true"
{{ end }}
{{ include "uno.common.label" . | indent 4 }}
type: "Opaque"
data:
  {{- if $previous }}
  KEYSTORE_PASSWORD: {{ $previous.data.KEYSTORE_PASSWORD }}
  {{- else }}
  KEYSTORE_PASSWORD: {{ randAlphaNum 8 | b64enc | quote }}
  {{- end }}
  DB_PASSWORD: {{ .Values.database.password |default "" | b64enc | quote }}
  KAFKA_PASSWORD: {{ .Values.kafka.password |default "" | b64enc | quote }}
