{
 "title": "UnO Dashboard - %NAMESPACE% - %RELEASE%",
 "tags": [ "hcl-uno" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "%NAMESPACE%" },
   { "name": "Release", "query": "%RELEASE%" },
   { "name": "cpuDur", "query": "[45s]" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{pod=~\"[[Release]]-.*\", namespace=~\"$Namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# UnO Dashboard\n* Namespace: %NAMESPACE%\n* Helm Release: %RELEASE%"
   }
  },
  { "title": "WA Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Jobs by status",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "round(avg(application_uno_orchestrator_jobs_count_jobs{namespace=~\"$Namespace\", release=~\"$Release\"} >= 0) by(namespace, jobstatus))",
     "legendFormat": "{{jobstatus}}"
    }
   ]
  },
  {
   "title": "Linked Workstations",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(folder) (sum by(folder, pod) (application_uno_workstation_linked_number{namespace=~\"$Namespace\", release=~\"$Release\"})>= 0)",
     "legendFormat": "{{folder}}"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"$Release-agentmanager\", namespace=~\"$Namespace\"}",
     "legendFormat": "agentmanager replica count"
    }
   ]
  },
  {
   "title": "Execution rate on orchestrator and scheduler",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "jobs/min" } },
   "targets": [
    {
     "expr": "sum by(app) (rate(application_uno_orchestrator_submission_count_number_total[$__rate_interval])) * 60",
     "legendFormat": "orchestrator submission rate"
    },
    {
     "expr": "sum by(app) (rate(application_uno_scheduler_submission_count_number_total[$__rate_interval])) * 60",
     "legendFormat": "scheduler submission rate"
    },
    {
     "expr": "sum by (app) (rate(application_uno_orchestrator_job_execution_delay_milliseconds_count[$__rate_interval])) * 60",
     "legendFormat": "completion rate"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"uno-stable-orchestrator|uno-stable-scheduler\"}",
     "legendFormat": "replicas of {{deployment}}"
    }
   ]
  },
  {
   "title": "Execution delay by workstation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (workstation) (rate(application_uno_orchestrator_job_execution_delay_milliseconds_sum [$__rate_interval])>=0 / rate(application_uno_orchestrator_job_execution_delay_milliseconds_count [$__rate_interval])>=0)",
     "legendFormat": "{{workstation}}"
    }
   ]
  },
  {
   "title": "Cloud Task Launcher running jobs by pod",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "jobs" } },
   "targets": [
    {
     "expr": "application_uno_cloud_executor_running_task_number",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Timer execution delay by type",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(type) (rate(application_uno_timer_task_execution_lag_milliseconds_sum[$__rate_interval])/rate(application_uno_timer_task_execution_lag_milliseconds_count[$__rate_interval]))>=0",
     "legendFormat": "{{workstation}}"
    }
   ]
  },
  { "title": "AI Agents Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Agent Conversation (last month)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Conversations"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_errors_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Errors"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_tool_errors_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Tool Errors"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_invoke_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Avg Invoke"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_genaicalls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} GenAI Calls"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Tools"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_response_time_monthly_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_invoke_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Avg Respnse Time"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_tool_duration_monthly_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Avg Tool Duration"
    }
   ]
  },
  {
   "title": "Tool Execution (last month)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "label_join(max by (agent, mode, workflow, service_name) (sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"workflow\", \"service_name\") ",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(max by (agent, mode, workflow, service_name) (sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_errors_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"workflow\", \"service_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(avg by (agent, mode, workflow, service_name) (sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_duration_monthly_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"workflow\", \"service_name\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agent Conversation (last 24h)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_conversations_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Conversations"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_errors_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Errors"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_tool_errors_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Tool Errors"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_invoke_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Avg Invoke"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_genaicalls_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} GenAI Calls"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_tool_calls_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_conversations_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Tools"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_response_time_daily_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_invoke_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Avg Respnse Time"
    },
    {
     "expr": "label_join(max by (agent, mode) (sum by (pod, agent, mode) (application_uno_aiagent_tool_duration_daily_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode) (application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\")",
     "legendFormat": "{{composite_key}} Avg Tool Duration"
    }
   ]
  },
  {
   "title": "Tool Execution (last 24h)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "label_join(max by (agent, mode, workflow, service_name) (sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_calls_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"workflow\", \"service_name\") ",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(max by (agent, mode, workflow, service_name) (sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_errors_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"workflow\", \"service_name\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(avg by (agent, mode, workflow, service_name) (sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_duration_daily_milliseconds{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}) / sum by (pod, agent, mode, workflow, service_name) (application_uno_aiagent_tool_calls_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"workflow\", \"service_name\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AI Agent Cost (Cloud Service)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_units_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "{{composite_key}} Daily Units"
    },
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_units_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "{{composite_key}} Monthly Units"
    }
   ]
  },
  {
   "title": "AI Agent Cost (BYOL)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_tokens_in_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_tokens_out_daily_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_cost_daily_dollars{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_tokens_in_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_tokens_out_monthly_number{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_join(max by (agent, mode, model) (sum by (pod, agent, mode, model) (application_uno_aiagent_cost_monthly_dollars{namespace=\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"})), \"composite_key\", \"-\", \"agent\", \"mode\", \"model\")",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AI Agent Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "AI Agent / Tool Calls per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (agent, mode) (\n  irate(application_uno_aiagent_invoke_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval])\n) * 60",
     "legendFormat": "Agent: {{agent}} - {{mode}}"
    },
    {
     "expr": "sum by (workflow, service_name, agent, mode) (\n  irate(application_uno_aiagent_tool_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval])\n) * 60\n",
     "legendFormat": "Tool: {{workflow}} - {{service_name}} - {{agent}} - {{mode}}"
    }
   ]
  },
  {
   "title": "AI Agent / Tool Errors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (agent, mode) (\n  irate(application_uno_aiagent_invoke_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\", status=\"ERROR\"}[$__rate_interval])\n) * 60",
     "legendFormat": "Agent: {{agent}} - {{mode}}"
    },
    {
     "expr": "sum by (workflow, service_name) (\n  irate(application_uno_aiagent_tool_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\", status=\"FAILED\"}[$__rate_interval])\n) * 60\n",
     "legendFormat": "Tool: {{workflow}} - {{service_name}}"
    }
   ]
  },
  {
   "title": "AI Agent Response time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 143 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (agent, mode, model) (\n  rate(application_uno_aiagent_invoke_seconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval])\n) / sum by (agent, mode, model) (\n  rate(application_uno_aiagent_invoke_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval])\n)",
     "legendFormat": "Agent: {{agent}} - {{mode}}"
    }
   ]
  },
  {
   "title": "Tool Duration",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (agent, mode, workflow, service_name) (\n  rate(application_uno_aiagent_tool_seconds_sum{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval])\n) / sum by (agent, mode, workflow, service_name) (\n  rate(application_uno_aiagent_tool_seconds_count{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"$pod\"}[$__rate_interval])\n)",
     "legendFormat": "Tool: {{workflow}} - {{service_name}} - {{agent}} - {{mode}}"
    }
   ]
  },
  { "title": "UnO License", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 } },
  {
   "title": "Consumed unique jobs in current month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 168 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(application_uno_orchestrator_license_job_count_number{namespace=~\"$Namespace\", release=~\"$Release\", period=\"month\", type=\"unique\"}>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 168 },
   "targets": [
    {
     "expr": "round(avg (application_uno_orchestrator_license_job_count_number{period=\"month\", namespace=~\"$Namespace\", release=~\"$Release\"}>0) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Jobs to send to license server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 172 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg (application_uno_orchestrator_license_job_to_send_jobs{namespace=~\"$Namespace\", release=~\"$Release\"}>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed AI Execution Units in current month",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 176 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(application_uno_aiagent_license_units_number{namespace=~\"$Namespace\", release=~\"$Release\", period=\"month\", type=\"total\"}>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed AI Execution Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 176 },
   "targets": [
    {
     "expr": "round(avg (application_uno_aiagent_license_units_number{period=\"month\", namespace=~\"$Namespace\", release=~\"$Release\"}>0) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "AI Execution Units to send to license server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 180 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg (application_uno_aiagent_license_units_to_send{namespace=~\"$Namespace\", release=~\"$Release\"}>0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GenAI Units by Agents in last 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 184 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  avg (\n    sum by (pod) (application_uno_aiagent_units_monthly_number{namespace=~\"$Namespace\", release=~\"$Release\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed GenAI Units (estimated)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 184 },
   "targets": [
    {
     "expr": "round(\n  avg (\n    sum by (pod) (application_uno_aiagent_units_monthly_number{namespace=~\"$Namespace\", release=~\"$Release\"})\n  ) +\n  sum (\n    increase(application_uno_genai_proxy_units_number_total{namespace=~\"$Namespace\", release=~\"$Release\"}[30d])\n  )\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "GenAI Units by Console in last 30 days (estimated)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 188 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n  sum (\n    increase(application_uno_genai_proxy_units_number_total{namespace=~\"$Namespace\", release=~\"$Release\"}[30d])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GenAI Cost (BYOL)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 192 } },
  {
   "title": "Cost last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 193 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (sum by (pod) (application_uno_genai_cost_daily_dollars{namespace=\"$Namespace\", release=~\"$Release\"}) or vector(0))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Monthly Scenario Stats",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 193 },
   "targets": [
    {
     "expr": "label_join(max by (scenario, platform, model) (sum by (pod, scenario, platform, model) (application_uno_genai_cost_monthly_dollars{namespace=\"$Namespace\", release=~\"$Release\"})), \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\")",
     "legendFormat": "{{composite_key}} (Cost)"
    },
    {
     "expr": "label_join(max by (scenario, platform, model) (sum by (pod, scenario, platform, model) (application_uno_genai_stats_monthly_number{namespace=\"$Namespace\", release=~\"$Release\"})), \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\")",
     "legendFormat": "{{composite_key}} (Count)"
    },
    {
     "expr": "label_join(max by (scenario, platform, model) (sum by (pod, scenario, platform, model) (application_uno_genai_tokens_in_monthly_number{namespace=\"$Namespace\", release=~\"$Release\"})), \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\")",
     "legendFormat": "{{composite_key}} (Count)"
    },
    {
     "expr": "label_join(max by (scenario, platform, model) (sum by (pod, scenario, platform, model) (application_uno_genai_tokens_out_monthly_number{namespace=\"$Namespace\", release=~\"$Release\"})), \"composite_key\", \"-\", \"scenario\", \"platform\", \"model\")",
     "legendFormat": "{{composite_key}} (Count)"
    }
   ]
  },
  {
   "title": "Cost last 30 days",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 197 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max (sum by (pod) (application_uno_genai_cost_monthly_dollars{namespace=\"$Namespace\", release=~\"$Release\"}) or vector(0))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Message processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 201 },
   "collapsed": true,
   "panels": [
    {
     "title": "rate of processed messages by topic",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(application_uno_message_process_milliseconds_count[$__rate_interval])>=0) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "rate of processed messages by message",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 213 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(application_uno_message_process_milliseconds_count[$__rate_interval])>=0) by (topic,messageType,messageSubType)",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    },
    {
     "title": "Message topic consumer lag",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 224 },
     "targets": [
      {
       "expr": "sum by(topic, service) (kafka_consumer_fetch_manager_records_lag{namespace=~\"$Namespace\"})",
       "legendFormat": "{{service}} / {{topic}}"
      }
     ]
    },
    {
     "title": "Processing usage by message type",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (topic,messageType,messageSubType) (rate (application_uno_message_process_milliseconds_sum[$__rate_interval]) >=0) / 1000",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    },
    {
     "title": "Average processing time by message type",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 245 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by(topic, messageType, messageSubType) ((rate (application_uno_message_process_milliseconds_sum[$__rate_interval]) / rate (application_uno_message_process_milliseconds_count[$__rate_interval]))>=0)",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    },
    {
     "title": "Message processing delay by topic",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 256 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg ((rate(application_uno_message_process_delay_milliseconds_sum [$__rate_interval])/rate(application_uno_message_process_delay_milliseconds_count [$__rate_interval]))>0)\n by (topic)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Message processing errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 267 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (topic, messageType, messageSubType) (rate (application_uno_message_process_errors_number_total [$__rate_interval]) >=0)",
       "legendFormat": "{{topic}} - {{messageType}} {{messageSubType}}"
      }
     ]
    }
   ]
  },
  {
   "title": "UnO PODs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 202 },
   "collapsed": true,
   "panels": [
    {
     "title": "POD replicas",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 279 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{deployment=~\"$Release-.*\", namespace=~\"$Namespace\"}",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "Failing Pods",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 289 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{namespace=~\"$Namespace\", phase=\"Failed\", pod=~\"[[pod]]\"}",
       "legendFormat": "{{namespace}} - {{ pod }}"
      }
     ]
    },
    {
     "title": "kube_pod_container_status_restarts_total",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 296 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(pod) (kube_pod_container_status_restarts_total{namespace=~\"$Namespace\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Pods CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 312 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "increase(container_cpu_usage_seconds_total{image=\"\"}[1m])/60",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "container_memory_usage_bytes & kube_pod_container_resource_limits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 325 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{namespace=~\"$Namespace\", pod=~\"[[pod]]\", container!=\"\"}) by (namespace, pod)",
       "legendFormat": "used by {{pod}}"
      },
      {
       "expr": "sum by(namespace, pod) (kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$Namespace\", pod=~\"$pod\", container!=\"\"})",
       "legendFormat": "limit for {{pod}}"
      }
     ]
    },
    {
     "title": " kube_pod_container_resource_limits - container_memory_usage_bytes",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 336 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(namespace, pod, container) (kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$Namespace\", pod=~\"$pod\", container!=\"\"}) - on(pod, namespace, container) sum(container_memory_usage_bytes{namespace=~\"$Namespace\", pod=~\"[[pod]]\", container!=\"\"}) by (namespace, pod, container)",
       "legendFormat": "available for {{pod}} on {{container}} {{namespace}}"
      }
     ]
    },
    {
     "title": "Live Threads",
     "type": "timeseries",
     "description": "The number of threads that are actively running tasks.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 346 },
     "targets": [
      {
       "expr": "sum(jvm_threads_live_threads{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"[[pod]]\"}) by (namespace,release,pod)",
       "legendFormat": "{{namespace}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Network I/O Pods (+Received / -Sent)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 357 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{ namespace=~\"$Namespace\", pod=~\"[[pod]]\"}[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "{{namespace}} - {{ pod }} - Received"
      },
      {
       "expr": "- sum (rate ( container_network_transmit_bytes_total{namespace=~\"$Namespace\", pod=~\"[[pod]]\"}[$__rate_interval] )) by (namespace, pod)",
       "legendFormat": "{{namespace}} - {{ pod }} - Sent"
      }
     ]
    },
    {
     "title": "kube_deployment_status_replicas & kube_statefulset_status_replicas_current",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 370 },
     "targets": [
      {
       "expr": "max(kube_deployment_status_replicas{namespace=\"$Namespace\"}) without (instance, pod)",
       "legendFormat": "{{deployment}}"
      },
      {
       "expr": "kube_statefulset_status_replicas_current{namespace=\"$Namespace\"}",
       "legendFormat": "{{statefulset}}"
      }
     ]
    },
    {
     "title": "kubelet_volume_stats_available_bytes by persistentvolumeclaim",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 381 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes)",
       "legendFormat": "{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 },
   "collapsed": true,
   "panels": [
    {
     "title": "kafka_consumer_request_rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(pod) (kafka_consumer_request_rate)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_consumer_fetch_manager_fetch_latency_avg",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 291 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (pod) (kafka_consumer_fetch_manager_fetch_latency_avg)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "kafka_producer_request_rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 302 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(pod) (kafka_producer_request_rate)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "agentmanager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 },
   "collapsed": true,
   "panels": [
    {
     "title": "application_uno_agentmanager_gw_connected_number",
     "type": "timeseries",
     "description": "The number of threads that are actively running tasks.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 427 },
     "targets": [
      {
       "expr": "application_uno_agentmanager_gw_connected_number",
       "legendFormat": "{{namespace}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Agent Gateway queue on Agent Manager",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 438 },
     "targets": [
      {
       "expr": "avg by(gw) (application_uno_agentmanager_command_queue_count_number{namespace=~\"$Namespace\"}>=0)",
       "legendFormat": "{{gw}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quarkus JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 205 },
   "collapsed": true,
   "panels": [
    {
     "title": "jvm_memory_max_bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 453 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod,namespace,release)(jvm_memory_max_bytes{ namespace=~\"$Namespace\", release=~\"$Release\",area=\"heap\", pod=~\"[[pod]]\"})",
       "legendFormat": "{{namespace}} - {{pod}} - {{release}}"
      }
     ]
    },
    {
     "title": "sum by (pod) (jvm_memory_max_bytes{area=\"heap\"})",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 462 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (pod) (jvm_memory_max_bytes{area=\"heap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes/jvm_memory_max_bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 473 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(pod,namespace,release)(jvm_memory_used_bytes{namespace=~\"$Namespace\", release=~\"$Release\",area=\"heap\", pod=~\"[[pod]]\"}) / sum by(pod,namespace,release)(jvm_memory_max_bytes{ namespace=~\"$Namespace\", release=~\"$Release\",area=\"heap\", pod=~\"[[pod]]\"})",
       "legendFormat": "{{namespace}} - {{pod}} - {{release}}"
      }
     ]
    },
    {
     "title": "jvm_gc_overhead_percent",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 482 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(jvm_gc_overhead_percent{namespace=~\"$Namespace\", release=~\"$Release\", pod=~\"[[pod]]\"}) by(namespace,release,pod)",
       "legendFormat": "{{namespace}} - {{release}} - {{pod}} "
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_max",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 490 },
     "targets": [
      {
       "expr": "sum by(pod) (jvm_gc_pause_seconds_max)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "WA console - Liberty metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 206 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Heap - Used Heap",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 504 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "base_memory_maxHeap_bytes{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{pod}} - {{__name__}}"
      },
      {
       "expr": "base_memory_usedHeap_bytes{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{pod}} - {{__name__}}"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 515 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{pod=~\".*waconsole.*\"}[$__rate_interval])/rate(base_gc_total{pod=~\".*waconsole.*\"}[$__rate_interval])",
       "legendFormat": "{{namespace}} - {{pod}} - {{name}}"
      }
     ]
    },
    {
     "title": "Live Sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 523 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vendor_session_liveSessions{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{appname}} "
      }
     ]
    },
    {
     "title": "Heap Usage Percentage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 532 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{pod=~\".*waconsole.*\"}/ base_memory_maxHeap_bytes{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{pod}} "
      }
     ]
    },
    {
     "title": "Active Sessions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 542 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vendor_session_activeSessions{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{appname}}"
      }
     ]
    },
    {
     "title": "Threadpool Size - Active Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 551 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vendor_threadpool_size{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{__name__}}"
      },
      {
       "expr": "vendor_threadpool_activeThreads{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{__name__}}"
      }
     ]
    }
   ]
  },
  {
   "title": "WA console - connection pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 207 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Time Usage per Connection",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 505 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_inUseTime_total_seconds{pod=~\".*waconsole.*\"}[$__rate_interval]) / rate(vendor_connectionpool_usedConnections_total{pod=~\".*waconsole.*\"}[$__rate_interval])>=0",
       "legendFormat": "{{namespace}} - {{release}} - {{pod}} "
      }
     ]
    },
    {
     "title": "Create - Destroy",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 514 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vendor_connectionpool_create_total{pod=~\".*waconsole.*\"} - vendor_connectionpool_destroy_total{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{pod}} "
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 522 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{__name__}} "
      },
      {
       "expr": "vendor_connectionpool_connectionHandles{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{__name__}} "
      },
      {
       "expr": "vendor_connectionpool_freeConnections{pod=~\".*waconsole.*\"}",
       "legendFormat": "{{namespace}} - {{release}} - {{__name__}} "
      }
     ]
    }
   ]
  }
 ]
}